version: 1
git_protocol: ssh
editor: vim
prompt: enabled
prefer_editor_prompt: disabled
pager:
aliases:
    co: pr checkout
http_unix_socket:
browser:
color_labels: enabled
accessible_colors: enabled
accessible_prompter: disabled
spinner: enabled
